"""Initial migration

Revision ID: 7469f35f2730
Revises: 
Create Date: 2025-08-11 22:32:32.222476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7469f35f2730'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_regiao', sa.String(), nullable=False),
    sa.Column('co_regiao', sa.Integer(), nullable=False),
    sa.Column('no_uf', sa.String(), nullable=False),
    sa.Column('sg_uf', sa.String(), nullable=False),
    sa.Column('co_uf', sa.Integer(), nullable=False),
    sa.Column('no_municipio', sa.String(), nullable=False),
    sa.Column('co_municipio', sa.Integer(), nullable=False),
    sa.Column('no_mesorregiao', sa.String(), nullable=False),
    sa.Column('co_mesorregiao', sa.Integer(), nullable=False),
    sa.Column('no_microrregiao', sa.String(), nullable=False),
    sa.Column('co_microrregiao', sa.Integer(), nullable=False),
    sa.Column('no_entidade', sa.String(), nullable=False),
    sa.Column('co_entidade', sa.Integer(), nullable=False),
    sa.Column('qt_mat_bas', sa.Integer(), nullable=True),
    sa.Column('qt_mat_inf', sa.Integer(), nullable=True),
    sa.Column('qt_mat_fund', sa.Integer(), nullable=True),
    sa.Column('qt_mat_med', sa.Integer(), nullable=True),
    sa.Column('qt_mat_eja', sa.Integer(), nullable=True),
    sa.Column('qt_mat_esp', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_instituicao')
    # ### end Alembic commands ###
